### ISSUE TITLE
how do i handle a non-existent cache value?

### ISSUE THREAD

**Issue by chovy** [patrickpissurno/vredis#5]
`cache := redis.get(key) or { panic(err) } `

this crashes the app if the key doesnj't exist.

**Comment by patrickpissurno** [comment]
Sorry for the huge delay. GitHub didn't send me a notification for this one.

I still didn't manage to set up some docs for the project so, for the time being, the best place to look for examples is in the [tests file](https://github.com/patrickpissurno/vredis/blob/master/vredis_test.v), as there you can find many snippets that cover pretty much all use cases.

So, answering your question, the way to do that would be:
```v
cache := redis.get(key) or {
    if err.msg == 'key not found' {
        //key doesn't exist, do something
    }
    else {
        //the error is something else, do something (eg. panic)
        panic(err)
    }
}
```

Hope it helps!

If you come across any further issues, feel free to reply here and I'll reopen the issue. Thanks!
